//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BKop.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_MAINVIEW                    105
#define IDR_MAINFRAME                   128
#define IDR_BKopTYPE                    129
#define IDD_DIALOG_DELETE               131
#define IDD_DIALOG_ROLE                 133
#define IDD_DIALOG_LOGIN                134
#define IDD_VIEW_ITEM                   136
#define IDD_DIALOG_SURROUND             138
#define IDD_DIALOG_NPC                  139
#define IDD_DIALOG_ITEMS                140
#define IDR_MENU_PACKAGE                141
#define IDD_DIALOG_SYSTEM               142
#define IDD_DIALOG_TALK                 144
#define IDD_DIALOG_MAP                  145
#define IDD_DIALOG_SCRIPT               146
#define IDD_DIALOG_SETUP                147
#define IDD_DIALOG_TOTAL_TALK_SESSION   148
#define IDD_DIALOG_PRIVATE_TALK_SESSION 149
#define IDR_MENU_TALK                   151
#define IDD_DIALOG_NORMAL_TALK_SESSION  152
#define IDD_DIALOG_AUTO_PUBLISH_MGR     153
#define IDC_TAB1                        1004
#define IDC_BUTTON_DELETE               1007
#define IDC_BUTTON_SELECTED_COUNT       1007
#define IDC_BUTTON7                     1009
#define IDC_COMBO_ROLE                  1011
#define IDC_BUTTON6                     1014
#define IDC_RICHEDIT23                  1016
#define IDC_STATIC_TOTAL_COUNT          1019
#define IDC_STATIC_NOW_COUNT            1020
#define IDC_STATIC_CHECK_COUNT          1021
#define IDC_STATIC_SELECTED_COUNT       1022
#define IDC_BUTTON_TOTAL_COUNT          1023
#define IDC_BUTTON_CHECK_COUNT          1024
#define IDC_BUTTON_NOW_COUNT            1025
#define IDC_CHECK_LOCK                  1026
#define IDC_COMBO_MODE                  1027
#define IDC_BUTTON_CLEAR                1028
#define IDC_RADIO1                      1029
#define IDC_BUTTON_COPY                 1029
#define IDC_RADIO2                      1030
#define IDC_BUTTON_ADD                  1030
#define IDC_RADIO3                      1031
#define IDC_LIST_ACCOUNT                1031
#define IDC_BUTTON_SAVE                 1032
#define IDC_RADIO4                      1032
#define IDC_BUTTON_LOAD                 1033
#define IDC_RADIO5                      1033
#define IDC_BUTTON_LOGIN                1034
#define IDC_RADIO6                      1034
#define IDC_EDIT_SERVER                 1035
#define IDC_EDIT_ACCOUNT                1036
#define IDC_EDIT_PASSWORD               1037
#define IDC_COMBO_SELECT_MAIN_PLAYER    1038
#define IDC_STATIC_SHEET_RECT           1039
#define IDC_CHECK_SET_THE_SAME          1040
#define IDC_PROGRESS_HP                 1042
#define IDC_PROGRESS_SP                 1043
#define IDC_PROGRESS_EXP                1044
#define IDC_STATIC_HP                   1045
#define IDC_STATIC_SP                   1046
#define IDC_STATIC_EXP                  1047
#define IDC_BUTTON_ADD_STR              1048
#define IDC_BUTTON_ADD_DEX              1049
#define IDC_BUTTON_ADD_AGI              1050
#define IDC_BUTTON_ADD_VIT              1051
#define IDC_BUTTON_ADD_STA              1052
#define IDC_BUTTON_ADD_LUK              1053
#define IDC_STATIC_NAME                 1054
#define IDC_STATIC_LEVEL                1055
#define IDC_STATIC_ATTRIBUTE_POINT      1056
#define IDC_STATIC_SKILL_POINT          1057
#define IDC_STATIC_EXP_PERCENT          1058
#define IDC_STATIC_STR                  1059
#define IDC_STATIC_DEX                  1060
#define IDC_STATIC_AGI                  1061
#define IDC_STATIC_VIT                  1062
#define IDC_STATIC_STA                  1063
#define IDC_STATIC_LUK                  1064
#define IDC_CHECK_DONT_RECONNECT        1065
#define IDC_LIST_STATE                  1066
#define IDC_STATIC_MONEY                1067
#define IDC_STATIC_MAP_NAME             1068
#define IDC_STATIC_MAP_POSITION         1069
#define IDC_LIST_PLAYERS                1070
#define IDC_LIST_MONSTER                1071
#define IDC_LIST_NPC                    1071
#define IDC_LIST_ITEMS                  1072
#define IDC_BUTTON_LOAD_MOVE_TABLE      1072
#define IDC_LIST_EQUIP                  1074
#define IDC_CHECK_AUTO_CREATE_DEL       1075
#define IDC_CHECK_SYSTEM_FILTER         1076
#define IDC_CHECK_DEBUG_FILTER          1077
#define IDC_RICHEDIT_SYSTEM             1078
#define IDC_COMBO_CHANNEL               1079
#define IDC_COMBO_TARGET                1080
#define IDC_COMBO_TEXT                  1081
#define IDC_BUTTON_SEND                 1082
#define IDC_RICHEDIT_TALK               1083
#define IDC_COMBO_COMMAND               1084
#define IDC_BUTTON_NAME_LIST            1085
#define IDC_LIST_PLAYER                 1086
#define IDC_BUTTON_AUTO_PUBLISH_MGR     1086
#define IDC_STATIC_IN                   1087
#define IDC_STATIC_OUT                  1088
#define IDC_RICHEDIT_TOTAL_TALK         1091
#define IDC_COMBO_SERVER                1092
#define IDC_EDIT1                       1093
#define IDC_EDIT_TEXT                   1093
#define IDC_COMBO1                      1094
#define IDC_COMBO2                      1095
#define IDC_DATETIMEPICKER1             1096
#define IDC_COMBO3                      1098
#define IDC_COMBO4                      1099
#define IDC_LIST_INFO                   1100
#define IDC_BUTTON_DEL                  1101
#define IDC_BUTTON1                     1103
#define IDC_BUTTON_GET_NOW_TIME         1103
#define ID_M_DROP                       32775
#define ID_M_INFO                       32777
#define ID_32774                        32778
#define ID_32771                        32780
#define ID_M_EQUIP                      32784
#define ID_M_USE                        32787
#define ID_M_UNEQUIP                    32788
#define ID_M_PICKUP                     32790
#define ID_MENU_CLEAR                   32792
#define ID_MENU_PRIVATE_CLEAR           32794
#define ID_MENU_PRIVATE                 32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
