print( "------------------------------------")
print( "-- Loading Shaitan Mirage files	  --")
print( "------------------------------------")
print( "* Loading ctrl.lua" )

function config(Map)
    MapCanSavePos(Map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(Map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(Map, 1)				-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(Map, 300)	-- 300 Players are allowed to enter the map
    MapCanTeam(Map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType(Map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )   
    MapCanStall(Map , 0)	
end

function get_map_entry_pos_shalan2()
	local POS_X = 1244
	local POS_Y = 3203
	return POS_X, POS_Y
end

function init_entry(Map)
    SetMapEntryMapName(Map, "magicsea")
    SetMapEntryTime(map, "2008/8/30/0/0", "0/4/0", "0/2/0", "0/2/0") --设置入口的时间，地图对象，首次开启时间（年/月/日/时/分），以后再次开启的间隔（日/时/分，全０表示只有首次开启），每次开启到入口消失的间隔（日/时/分，全０表示永不消失），每次开启到地图关闭的间隔（日/时/分，全０表示永不关闭）。。
end

function after_enter_shalan2(Player, MapCopy)
end

function before_leave_shalan2(Player)
end

function map_copy_first_run_shalan2(MapCopy)
end

function map_copy_run_shalan2(MapCopy)
end

function map_copy_run_special_shalan2(Map)
end

function map_run_shalan2(Map)
end

function map_copy_before_close_shalan2(MapCopy)
end

function map_copy_close_shalan2(MapCopy)
end

function can_open_entry_shalan2(Map) 
end 