print( "------------------------------------")
print( "-- Loading Icicle Mirage files    --")
print( "------------------------------------")
print( "* Loading ctrl.lua" )

function config(Map)
    MapCanSavePos(Map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(Map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(Map, 1)				-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(Map, 300)	-- 300 Players are allowed to enter the map
    MapCanTeam(Map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType(Map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )   
    MapCanStall(Map , 0)	
end


function get_map_entry_pos_binglang2()
	local POS_X = 2718
	local POS_Y = 659
	return POS_X, POS_Y
end

function init_entry(Map)
    SetMapEntryMapName(Map, "darkblue")
    SetMapEntryTime(map, "2008/8/30/0/0", "0/4/0", "0/2/0", "0/2/0")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)
end

function after_enter_binglang2(Player, MapCopy) 
end

function before_leave_binglang2(Player)
end

function map_copy_first_run_binglang2(MapCopy)
end

function map_copy_run_binglang2(MapCopy)
end

function map_copy_run_special_binglang2(Map)
end

function map_run_binglang2(Map)
end

function map_copy_before_close_binglang2(MapCopy)
end

function map_copy_close_binglang2(MapCopy)
end

function can_open_entry_binglang2(Map) 
end 