--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua by By FlashStep		--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading Hellchapter Ctrl.lua" )

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    MapCopyStartType(map, 1) 		-- 设置地图立即开始
    SingleMapCopyPlyNum(map, 300) 	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 1 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end


function get_map_entry_pos_Hellchapter()   --设置入口的位置的坐标（坐标（米））

	local POS_X=410
	local POS_Y=612
	return POS_X , POS_Y

end

function init_entry(map)

    SetMapEntryMapName(map, "DreamIsland") --
    SetMapEntryTime(map, "2005/8/30/0/0", "0/0/0", "0/0/0", "0/0/0")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)
   
end

function after_enter_Hellchapter( role , map_copy )

end

function before_leave_Hellchapter( role )

end

function map_copy_first_run_Hellchapter( map_copy )

end

function map_copy_run_Hellchapter( map_copy )


end

--每5秒执行一次的
function map_run_Hellchapter( map )

end

--地图关闭时执行
function map_copy_close_Hellchapter( map_copy )


end