--Hook:AddPostHook("cha_timer", cha_timer_hook,1)
--Hook:AddPostHook("GetExp_New", custom_GetExp_New, 1)

dofile(GetResPath("script/extension/Tools.lua"))
dofile(GetResPath("script/extension/ItemUsage.lua"))
dofile(GetResPath("script/extension/hook.lua"))
dofile(GetResPath("script/extension/serialize.lua"))
dofile(GetResPath("script/extension/ModuleStatev.lua"))
dofile(GetResPath("script/extension/IGS.lua"))
dofile(GetResPath("script/extension/ChatHandler.lua"))
dofile(GetResPath("script/extension/freeLunch.lua"))
dofile(GetResPath("script/extension/salt.lua"))
dofile(GetResPath("script/extension/itempre.lua"))
dofile(GetResPath("script/extension/forge-combine.lua"))
dofile(GetResPath("script/extension/itemupgrade.lua"))
dofile(GetResPath("script/extension/AdmiralCloak.lua"))
dofile(GetResPath("script/extension/Tribulation.lua"))