--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading Hell2 Ctrl.lua" )


function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    MapCopyStartType(map, 1) 		-- 设置地图立即开始
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end

function get_map_entry_pos_hell2()

	local POS_X=72
	local POS_Y=179
	return POS_X , POS_Y

end

function init_entry(map)
    SetMapEntryMapName(map, "hell")
    SetMapEntryTime(map, "2007/1/19/11/30", "1/0/0", "0/0/30", "0/5/30")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)

end

function after_enter_hell2( role , map_copy )

local cha_name=GetChaDefaultName(role)

SystemNotice ( role, "Mysterious voice: Not bad, <"..cha_name..">, to be able to survive till here. If you can cross the water in front, I'll acknowledge your capabilities!" ) 

end

function before_leave_hell2 ( role )

end

function map_copy_first_run_hell2( map_copy )

end

function map_copy_run_hell2( map_copy )

			
	if CheckMonsterDead ( AZRAEL[9] ) == 1 then
		
		if CRY[9]==0 then
			local Notice_all = "Kuroo: The ancient curse has already activated. You will awaken the most deepest evil when you pass through. May death bring you peace!!!"
			MapCopyNotice ( map_copy , Notice_all )
			CRY[9]=1
		end
	end
		
	if CRY[9]==1  then
		
		if HELLCLOSETIME==300 then

			Notice ("Mysterious Voice: Not bad, warriors. You even managed to kill my last pet. But do you remember what happen previously? You now have only 4 mins.")
			HELLCLOSETIME = HELLCLOSETIME - 60
		end

		local closetime = HELLCLOSETIME
		for i = 1 , MAXNOTICE , 1 do
			if closetime ==NOTICETIME[i] then
				local Notice_all = "Warning! Collapse of Abaddon 9 left "..closetime.." sec(s)! All adventurer prepare to hide"
				MapCopyNotice ( map_copy ,Notice_all )
			end
		end
		HELLCLOSETIME = HELLCLOSETIME-1

		if HELLCLOSETIME == 0 then


			HELLCLOSETIME = 300
			CRY[9]=0
			CloseMapEntry ( "hell2" )
			CloseMapCopy ( "hell2" )

		end
	end
end

function map_run_hell2( map )

end

function map_copy_close_hell2 ( map_copy )

			HELLCLOSETIME = 300
			CRY[9]=0

end

function can_open_entry_hell2( map ) 
	--local time = GetTickCount ( ) 
	local Now_Week = GetNowWeek()
	if Now_Week >=5 and Now_Week < 7 then
		return 1
	end

		return 0

end